// BH66F2650.h
//	This file contains the definition of registers for
//		Holtek BH66F2650 microcontroller.
//	Generated by HTFileParse.dll.
//	[VERSION] 1.8, 4
// Do not modify manually.

#ifndef _BH66F2650_H_
#define _BH66F2650_H_

#ifndef __DISABLE_HGCC_BUILD_IN__
#include "build-in.h"
#endif

#define DEFINE_ISR(isr_name, vector) void __attribute((interrupt(vector))) isr_name(void)

#define DEFINE_SFR(sfr_type, sfr, addr) static volatile sfr_type sfr __attribute__ ((at(addr)))

typedef unsigned char __sfr_byte;

typedef struct {
	unsigned char __c : 1;
	unsigned char __ac : 1;
	unsigned char __z : 1;
	unsigned char __ov : 1;
	unsigned char __pdf : 1;
	unsigned char __to : 1;
	unsigned char __cz : 1;
	unsigned char __sc : 1;
} __status_bits;

typedef union {
	__status_bits bits;
	__sfr_byte byte;
} __status_type;

typedef struct {
	unsigned char __wrf : 1;
	unsigned char __lrf : 1;
	unsigned char __lvrf : 1;
	unsigned char __rstf : 1;
	unsigned char : 4;
} __rstfc_bits;

typedef union {
	__rstfc_bits bits;
	__sfr_byte byte;
} __rstfc_type;

typedef struct {
	unsigned char __fsiden : 1;
	unsigned char __fhiden : 1;
	unsigned char __fss : 1;
	unsigned char __fhs : 1;
	unsigned char : 1;
	unsigned char __cks0 : 1;
	unsigned char __cks1 : 1;
	unsigned char __cks2 : 1;
} __scc_bits;

typedef union {
	__scc_bits bits;
	__sfr_byte byte;
} __scc_type;

typedef struct {
	unsigned char __hircen : 1;
	unsigned char __hircf : 1;
	unsigned char __hirc0 : 1;
	unsigned char __hirc1 : 1;
	unsigned char : 4;
} __hircc_bits;

typedef union {
	__hircc_bits bits;
	__sfr_byte byte;
} __hircc_type;

typedef struct {
	unsigned char __hxten : 1;
	unsigned char __hxtf : 1;
	unsigned char __hxtm : 1;
	unsigned char : 5;
} __hxtc_bits;

typedef union {
	__hxtc_bits bits;
	__sfr_byte byte;
} __hxtc_type;

typedef struct {
	unsigned char __lxten : 1;
	unsigned char __lxtf : 1;
	unsigned char : 6;
} __lxtc_bits;

typedef union {
	__lxtc_bits bits;
	__sfr_byte byte;
} __lxtc_type;

typedef struct {
	unsigned char __pa0 : 1;
	unsigned char __pa1 : 1;
	unsigned char __pa2 : 1;
	unsigned char __pa3 : 1;
	unsigned char __pa4 : 1;
	unsigned char __pa5 : 1;
	unsigned char __pa6 : 1;
	unsigned char __pa7 : 1;
} __pa_bits;

typedef union {
	__pa_bits bits;
	__sfr_byte byte;
} __pa_type;

typedef struct {
	unsigned char __pac0 : 1;
	unsigned char __pac1 : 1;
	unsigned char __pac2 : 1;
	unsigned char __pac3 : 1;
	unsigned char __pac4 : 1;
	unsigned char __pac5 : 1;
	unsigned char __pac6 : 1;
	unsigned char __pac7 : 1;
} __pac_bits;

typedef union {
	__pac_bits bits;
	__sfr_byte byte;
} __pac_type;

typedef struct {
	unsigned char __papu0 : 1;
	unsigned char __papu1 : 1;
	unsigned char __papu2 : 1;
	unsigned char __papu3 : 1;
	unsigned char __papu4 : 1;
	unsigned char __papu5 : 1;
	unsigned char __papu6 : 1;
	unsigned char __papu7 : 1;
} __papu_bits;

typedef union {
	__papu_bits bits;
	__sfr_byte byte;
} __papu_type;

typedef struct {
	unsigned char __pawu0 : 1;
	unsigned char __pawu1 : 1;
	unsigned char __pawu2 : 1;
	unsigned char __pawu3 : 1;
	unsigned char __pawu4 : 1;
	unsigned char __pawu5 : 1;
	unsigned char __pawu6 : 1;
	unsigned char __pawu7 : 1;
} __pawu_bits;

typedef union {
	__pawu_bits bits;
	__sfr_byte byte;
} __pawu_type;

typedef struct {
	unsigned char __rstc0 : 1;
	unsigned char __rstc1 : 1;
	unsigned char __rstc2 : 1;
	unsigned char __rstc3 : 1;
	unsigned char __rstc4 : 1;
	unsigned char __rstc5 : 1;
	unsigned char __rstc6 : 1;
	unsigned char __rstc7 : 1;
} __rstc_bits;

typedef union {
	__rstc_bits bits;
	__sfr_byte byte;
} __rstc_type;

typedef struct {
	unsigned char __lvs0 : 1;
	unsigned char __lvs1 : 1;
	unsigned char __lvs2 : 1;
	unsigned char __lvs3 : 1;
	unsigned char __lvs4 : 1;
	unsigned char __lvs5 : 1;
	unsigned char __lvs6 : 1;
	unsigned char __lvs7 : 1;
} __lvrc_bits;

typedef union {
	__lvrc_bits bits;
	__sfr_byte byte;
} __lvrc_type;

typedef struct {
	unsigned char __vlvd0 : 1;
	unsigned char __vlvd1 : 1;
	unsigned char __vlvd2 : 1;
	unsigned char __vbgen : 1;
	unsigned char __lvden : 1;
	unsigned char __lvdo : 1;
	unsigned char : 2;
} __lvdc_bits;

typedef union {
	__lvdc_bits bits;
	__sfr_byte byte;
} __lvdc_type;

typedef struct {
	unsigned char __stmpe : 1;
	unsigned char __stmae : 1;
	unsigned char __ptm0pe : 1;
	unsigned char __ptm0ae : 1;
	unsigned char __stmpf : 1;
	unsigned char __stmaf : 1;
	unsigned char __ptm0pf : 1;
	unsigned char __ptm0af : 1;
} __mfi0_bits;

typedef union {
	__mfi0_bits bits;
	__sfr_byte byte;
} __mfi0_type;

typedef struct {
	unsigned char __ptm1pe : 1;
	unsigned char __ptm1ae : 1;
	unsigned char __ptm2pe : 1;
	unsigned char __ptm2ae : 1;
	unsigned char __ptm1pf : 1;
	unsigned char __ptm1af : 1;
	unsigned char __ptm2pf : 1;
	unsigned char __ptm2af : 1;
} __mfi1_bits;

typedef union {
	__mfi1_bits bits;
	__sfr_byte byte;
} __mfi1_type;

typedef struct {
	unsigned char __lve : 1;
	unsigned char __dee : 1;
	unsigned char : 2;
	unsigned char __lvf : 1;
	unsigned char __def : 1;
	unsigned char : 2;
} __mfi2_bits;

typedef union {
	__mfi2_bits bits;
	__sfr_byte byte;
} __mfi2_type;

typedef struct {
	unsigned char __ws0 : 1;
	unsigned char __ws1 : 1;
	unsigned char __ws2 : 1;
	unsigned char __we0 : 1;
	unsigned char __we1 : 1;
	unsigned char __we2 : 1;
	unsigned char __we3 : 1;
	unsigned char __we4 : 1;
} __wdtc_bits;

typedef union {
	__wdtc_bits bits;
	__sfr_byte byte;
} __wdtc_type;

typedef struct {
	unsigned char __int0s0 : 1;
	unsigned char __int0s1 : 1;
	unsigned char __int1s0 : 1;
	unsigned char __int1s1 : 1;
	unsigned char : 4;
} __integ_bits;

typedef union {
	__integ_bits bits;
	__sfr_byte byte;
} __integ_type;

typedef struct {
	unsigned char __emi : 1;
	unsigned char __int0e : 1;
	unsigned char __int1e : 1;
	unsigned char __ade : 1;
	unsigned char __int0f : 1;
	unsigned char __int1f : 1;
	unsigned char __adf : 1;
	unsigned char : 1;
} __intc0_bits;

typedef union {
	__intc0_bits bits;
	__sfr_byte byte;
} __intc0_type;

typedef struct {
	unsigned char __mf0e : 1;
	unsigned char __mf1e : 1;
	unsigned char __mf2e : 1;
	unsigned char : 1;
	unsigned char __mf0f : 1;
	unsigned char __mf1f : 1;
	unsigned char __mf2f : 1;
	unsigned char : 1;
} __intc1_bits;

typedef union {
	__intc1_bits bits;
	__sfr_byte byte;
} __intc1_type;

typedef struct {
	unsigned char __tb0e : 1;
	unsigned char __tb1e : 1;
	unsigned char __ure : 1;
	unsigned char __sime : 1;
	unsigned char __tb0f : 1;
	unsigned char __tb1f : 1;
	unsigned char __urf : 1;
	unsigned char __simf : 1;
} __intc2_bits;

typedef union {
	__intc2_bits bits;
	__sfr_byte byte;
} __intc2_type;

typedef struct {
	unsigned char __spiae : 1;
	unsigned char : 3;
	unsigned char __spiaf : 1;
	unsigned char : 3;
} __intc3_bits;

typedef union {
	__intc3_bits bits;
	__sfr_byte byte;
} __intc3_type;

typedef struct {
	unsigned char __pb0 : 1;
	unsigned char __pb1 : 1;
	unsigned char __pb2 : 1;
	unsigned char __pb3 : 1;
	unsigned char __pb4 : 1;
	unsigned char __pb5 : 1;
	unsigned char __pb6 : 1;
	unsigned char __pb7 : 1;
} __pb_bits;

typedef union {
	__pb_bits bits;
	__sfr_byte byte;
} __pb_type;

typedef struct {
	unsigned char __pbc0 : 1;
	unsigned char __pbc1 : 1;
	unsigned char __pbc2 : 1;
	unsigned char __pbc3 : 1;
	unsigned char __pbc4 : 1;
	unsigned char __pbc5 : 1;
	unsigned char __pbc6 : 1;
	unsigned char __pbc7 : 1;
} __pbc_bits;

typedef union {
	__pbc_bits bits;
	__sfr_byte byte;
} __pbc_type;

typedef struct {
	unsigned char __pbpu0 : 1;
	unsigned char __pbpu1 : 1;
	unsigned char __pbpu2 : 1;
	unsigned char __pbpu3 : 1;
	unsigned char __pbpu4 : 1;
	unsigned char __pbpu5 : 1;
	unsigned char __pbpu6 : 1;
	unsigned char __pbpu7 : 1;
} __pbpu_bits;

typedef union {
	__pbpu_bits bits;
	__sfr_byte byte;
} __pbpu_type;

typedef struct {
	unsigned char __pc0 : 1;
	unsigned char __pc1 : 1;
	unsigned char __pc2 : 1;
	unsigned char __pc3 : 1;
	unsigned char __pc4 : 1;
	unsigned char __pc5 : 1;
	unsigned char __pc6 : 1;
	unsigned char __pc7 : 1;
} __pc_bits;

typedef union {
	__pc_bits bits;
	__sfr_byte byte;
} __pc_type;

typedef struct {
	unsigned char __pcc0 : 1;
	unsigned char __pcc1 : 1;
	unsigned char __pcc2 : 1;
	unsigned char __pcc3 : 1;
	unsigned char __pcc4 : 1;
	unsigned char __pcc5 : 1;
	unsigned char __pcc6 : 1;
	unsigned char __pcc7 : 1;
} __pcc_bits;

typedef union {
	__pcc_bits bits;
	__sfr_byte byte;
} __pcc_type;

typedef struct {
	unsigned char __pcpu0 : 1;
	unsigned char __pcpu1 : 1;
	unsigned char __pcpu2 : 1;
	unsigned char __pcpu3 : 1;
	unsigned char __pcpu4 : 1;
	unsigned char __pcpu5 : 1;
	unsigned char __pcpu6 : 1;
	unsigned char __pcpu7 : 1;
} __pcpu_bits;

typedef union {
	__pcpu_bits bits;
	__sfr_byte byte;
} __pcpu_type;

typedef struct {
	unsigned char __clksel0 : 1;
	unsigned char __clksel1 : 1;
	unsigned char : 6;
} __pscr_bits;

typedef union {
	__pscr_bits bits;
	__sfr_byte byte;
} __pscr_type;

typedef struct {
	unsigned char __tb00 : 1;
	unsigned char __tb01 : 1;
	unsigned char __tb02 : 1;
	unsigned char : 4;
	unsigned char __tb0on : 1;
} __tb0c_bits;

typedef union {
	__tb0c_bits bits;
	__sfr_byte byte;
} __tb0c_type;

typedef struct {
	unsigned char __tb10 : 1;
	unsigned char __tb11 : 1;
	unsigned char __tb12 : 1;
	unsigned char : 4;
	unsigned char __tb1on : 1;
} __tb1c_bits;

typedef union {
	__tb1c_bits bits;
	__sfr_byte byte;
} __tb1c_type;

typedef struct {
	unsigned char __txif : 1;
	unsigned char __tidle : 1;
	unsigned char __rxif : 1;
	unsigned char __ridle : 1;
	unsigned char __oerr : 1;
	unsigned char __ferr : 1;
	unsigned char __nf : 1;
	unsigned char __perr : 1;
} __usr_bits;

typedef union {
	__usr_bits bits;
	__sfr_byte byte;
} __usr_type;

typedef struct {
	unsigned char __tx8 : 1;
	unsigned char __rx8 : 1;
	unsigned char __txbrk : 1;
	unsigned char __stops : 1;
	unsigned char __prt : 1;
	unsigned char __pren : 1;
	unsigned char __bno : 1;
	unsigned char __uarten : 1;
} __ucr1_bits;

typedef union {
	__ucr1_bits bits;
	__sfr_byte byte;
} __ucr1_type;

typedef struct {
	unsigned char __teie : 1;
	unsigned char __tiie : 1;
	unsigned char __rie : 1;
	unsigned char __wake : 1;
	unsigned char __adden : 1;
	unsigned char __brgh : 1;
	unsigned char __rxen : 1;
	unsigned char __txen : 1;
} __ucr2_bits;

typedef union {
	__ucr2_bits bits;
	__sfr_byte byte;
} __ucr2_type;

typedef struct {
	unsigned char __simicf : 1;
	unsigned char __simen : 1;
	unsigned char __simdeb0 : 1;
	unsigned char __simdeb1 : 1;
	unsigned char : 1;
	unsigned char __sim0 : 1;
	unsigned char __sim1 : 1;
	unsigned char __sim2 : 1;
} __simc0_bits;

typedef union {
	__simc0_bits bits;
	__sfr_byte byte;
} __simc0_type;

typedef struct {
	unsigned char __rxak : 1;
	unsigned char __iamwu : 1;
	unsigned char __srw : 1;
	unsigned char __txak : 1;
	unsigned char __htx : 1;
	unsigned char __hbb : 1;
	unsigned char __haas : 1;
	unsigned char __hcf : 1;
} __simc1_bits;

typedef union {
	__simc1_bits bits;
	__sfr_byte byte;
} __simc1_type;

typedef struct {
	unsigned char __trf : 1;
	unsigned char __wcol : 1;
	unsigned char __csen : 1;
	unsigned char __mls : 1;
	unsigned char __ckeg : 1;
	unsigned char __ckpolb : 1;
	unsigned char : 2;
} __simc2_bits;

typedef union {
	__simc2_bits bits;
	__sfr_byte byte;
} __simc2_type;

typedef struct {
	unsigned char __simtos0 : 1;
	unsigned char __simtos1 : 1;
	unsigned char __simtos2 : 1;
	unsigned char __simtos3 : 1;
	unsigned char __simtos4 : 1;
	unsigned char __simtos5 : 1;
	unsigned char __simtof : 1;
	unsigned char __simtoen : 1;
} __simtoc_bits;

typedef union {
	__simtoc_bits bits;
	__sfr_byte byte;
} __simtoc_type;

typedef struct {
	unsigned char __spiaicf : 1;
	unsigned char __spiaen : 1;
	unsigned char : 3;
	unsigned char __saspi0 : 1;
	unsigned char __saspi1 : 1;
	unsigned char __saspi2 : 1;
} __spiac0_bits;

typedef union {
	__spiac0_bits bits;
	__sfr_byte byte;
} __spiac0_type;

typedef struct {
	unsigned char __satrf : 1;
	unsigned char __sawcol : 1;
	unsigned char __sacsen : 1;
	unsigned char __samls : 1;
	unsigned char __sackeg : 1;
	unsigned char __sackpolb : 1;
	unsigned char : 2;
} __spiac1_bits;

typedef union {
	__spiac1_bits bits;
	__sfr_byte byte;
} __spiac1_type;

typedef struct {
	unsigned char __eea0 : 1;
	unsigned char __eea1 : 1;
	unsigned char __eea2 : 1;
	unsigned char __eea3 : 1;
	unsigned char __eea4 : 1;
	unsigned char __eea5 : 1;
	unsigned char : 2;
} __eea_bits;

typedef union {
	__eea_bits bits;
	__sfr_byte byte;
} __eea_type;

typedef struct {
	unsigned char __eed0 : 1;
	unsigned char __eed1 : 1;
	unsigned char __eed2 : 1;
	unsigned char __eed3 : 1;
	unsigned char __eed4 : 1;
	unsigned char __eed5 : 1;
	unsigned char __eed6 : 1;
	unsigned char __eed7 : 1;
} __eed_bits;

typedef union {
	__eed_bits bits;
	__sfr_byte byte;
} __eed_type;

typedef struct {
	unsigned char : 3;
	unsigned char __ston : 1;
	unsigned char __stck0 : 1;
	unsigned char __stck1 : 1;
	unsigned char __stck2 : 1;
	unsigned char __stpau : 1;
} __stmc0_bits;

typedef union {
	__stmc0_bits bits;
	__sfr_byte byte;
} __stmc0_type;

typedef struct {
	unsigned char __stcclr : 1;
	unsigned char __stdpx : 1;
	unsigned char __stpol : 1;
	unsigned char __stoc : 1;
	unsigned char __stio0 : 1;
	unsigned char __stio1 : 1;
	unsigned char __stm0 : 1;
	unsigned char __stm1 : 1;
} __stmc1_bits;

typedef union {
	__stmc1_bits bits;
	__sfr_byte byte;
} __stmc1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt0on : 1;
	unsigned char __pt0ck0 : 1;
	unsigned char __pt0ck1 : 1;
	unsigned char __pt0ck2 : 1;
	unsigned char __pt0pau : 1;
} __ptm0c0_bits;

typedef union {
	__ptm0c0_bits bits;
	__sfr_byte byte;
} __ptm0c0_type;

typedef struct {
	unsigned char __pt0cclr : 1;
	unsigned char __pt0capts : 1;
	unsigned char __pt0pol : 1;
	unsigned char __pt0oc : 1;
	unsigned char __pt0io0 : 1;
	unsigned char __pt0io1 : 1;
	unsigned char __pt0m0 : 1;
	unsigned char __pt0m1 : 1;
} __ptm0c1_bits;

typedef union {
	__ptm0c1_bits bits;
	__sfr_byte byte;
} __ptm0c1_type;

typedef struct {
	unsigned char : 6;
	unsigned char __mdwov : 1;
	unsigned char __mdwef : 1;
} __mduwctrl_bits;

typedef union {
	__mduwctrl_bits bits;
	__sfr_byte byte;
} __mduwctrl_type;

typedef struct {
	unsigned char __adck0 : 1;
	unsigned char __adck1 : 1;
	unsigned char __adck2 : 1;
	unsigned char __adck3 : 1;
	unsigned char __adck4 : 1;
	unsigned char : 3;
} __adcs_bits;

typedef union {
	__adcs_bits bits;
	__sfr_byte byte;
} __adcs_type;

typedef struct {
	unsigned char __vrefs : 1;
	unsigned char : 1;
	unsigned char __ador0 : 1;
	unsigned char __ador1 : 1;
	unsigned char __ador2 : 1;
	unsigned char __adoff : 1;
	unsigned char __adslp : 1;
	unsigned char __adrst : 1;
} __adcr0_bits;

typedef union {
	__adcr0_bits bits;
	__sfr_byte byte;
} __adcr0_type;

typedef struct {
	unsigned char : 1;
	unsigned char __eoc : 1;
	unsigned char __adcdl : 1;
	unsigned char __vrbufp : 1;
	unsigned char __vrbufn : 1;
	unsigned char __flms0 : 1;
	unsigned char __flms1 : 1;
	unsigned char __flms2 : 1;
} __adcr1_bits;

typedef union {
	__adcr1_bits bits;
	__sfr_byte byte;
} __adcr1_type;

typedef struct {
	unsigned char __ldovs0 : 1;
	unsigned char __ldovs1 : 1;
	unsigned char __ldobps : 1;
	unsigned char : 4;
	unsigned char __ldoen : 1;
} __pwrc_bits;

typedef union {
	__pwrc_bits bits;
	__sfr_byte byte;
} __pwrc_type;

typedef struct {
	unsigned char __pgs0 : 1;
	unsigned char __pgs1 : 1;
	unsigned char __pgs2 : 1;
	unsigned char __ags0 : 1;
	unsigned char __ags1 : 1;
	unsigned char __vgs0 : 1;
	unsigned char __vgs1 : 1;
	unsigned char : 1;
} __pgac0_bits;

typedef union {
	__pgac0_bits bits;
	__sfr_byte byte;
} __pgac0_type;

typedef struct {
	unsigned char : 1;
	unsigned char __dcset0 : 1;
	unsigned char __dcset1 : 1;
	unsigned char __dcset2 : 1;
	unsigned char __inx0 : 1;
	unsigned char __inx1 : 1;
	unsigned char __inis : 1;
	unsigned char : 1;
} __pgac1_bits;

typedef union {
	__pgac1_bits bits;
	__sfr_byte byte;
} __pgac1_type;

typedef struct {
	unsigned char __chsp0 : 1;
	unsigned char __chsp1 : 1;
	unsigned char __chsp2 : 1;
	unsigned char __chsp3 : 1;
	unsigned char __chsn0 : 1;
	unsigned char __chsn1 : 1;
	unsigned char __chsn2 : 1;
	unsigned char __chsn3 : 1;
} __pgacs_bits;

typedef union {
	__pgacs_bits bits;
	__sfr_byte byte;
} __pgacs_type;

typedef struct {
	unsigned char : 5;
	unsigned char __dsdacvrs0 : 1;
	unsigned char __dsdacvrs1 : 1;
	unsigned char __dsdacen : 1;
} __dsdacc_bits;

typedef union {
	__dsdacc_bits bits;
	__sfr_byte byte;
} __dsdacc_type;

typedef struct {
	unsigned char : 4;
	unsigned char __bren : 1;
	unsigned char __d0 : 1;
	unsigned char __d1 : 1;
	unsigned char __sgen : 1;
} __sgc_bits;

typedef union {
	__sgc_bits bits;
	__sfr_byte byte;
} __sgc_type;

typedef struct {
	unsigned char __op2g0 : 1;
	unsigned char __op2g1 : 1;
	unsigned char __op2g2 : 1;
	unsigned char __op2g3 : 1;
	unsigned char : 3;
	unsigned char __opaen : 1;
} __opac_bits;

typedef union {
	__opac_bits bits;
	__sfr_byte byte;
} __opac_type;

typedef struct {
	unsigned char __vfl2 : 1;
	unsigned char __ifl1 : 1;
	unsigned char __vfr1 : 1;
	unsigned char __ifr2 : 1;
	unsigned char __vhl2 : 1;
	unsigned char __ihl1 : 1;
	unsigned char __vhr1 : 1;
	unsigned char __ihr2 : 1;
} __swc0_bits;

typedef union {
	__swc0_bits bits;
	__sfr_byte byte;
} __swc0_type;

typedef struct {
	unsigned char __irf2 : 1;
	unsigned char __vrfp2 : 1;
	unsigned char __irf1 : 1;
	unsigned char __vrfp1 : 1;
	unsigned char __vrfn : 1;
	unsigned char __ihl2 : 1;
	unsigned char __vhl1 : 1;
	unsigned char : 1;
} __swc1_bits;

typedef union {
	__swc1_bits bits;
	__sfr_byte byte;
} __swc1_type;

typedef struct {
	unsigned char : 1;
	unsigned char __ifr1 : 1;
	unsigned char __ifl2 : 1;
	unsigned char __vfr2 : 1;
	unsigned char __vfl1 : 1;
	unsigned char __ihr1 : 1;
	unsigned char __vhr2 : 1;
	unsigned char : 1;
} __swc2_bits;

typedef union {
	__swc2_bits bits;
	__sfr_byte byte;
} __swc2_type;

typedef struct {
	unsigned char __sw18 : 1;
	unsigned char __sw19 : 1;
	unsigned char : 2;
	unsigned char __hysen : 1;
	unsigned char : 2;
	unsigned char __ftren : 1;
} __ftrc_bits;

typedef union {
	__ftrc_bits bits;
	__sfr_byte byte;
} __ftrc_type;

typedef struct {
	unsigned char __pd0 : 1;
	unsigned char __pd1 : 1;
	unsigned char __pd2 : 1;
	unsigned char __pd3 : 1;
	unsigned char : 4;
} __pd_bits;

typedef union {
	__pd_bits bits;
	__sfr_byte byte;
} __pd_type;

typedef struct {
	unsigned char __pdc0 : 1;
	unsigned char __pdc1 : 1;
	unsigned char __pdc2 : 1;
	unsigned char __pdc3 : 1;
	unsigned char : 4;
} __pdc_bits;

typedef union {
	__pdc_bits bits;
	__sfr_byte byte;
} __pdc_type;

typedef struct {
	unsigned char __pdpu0 : 1;
	unsigned char __pdpu1 : 1;
	unsigned char __pdpu2 : 1;
	unsigned char __pdpu3 : 1;
	unsigned char : 4;
} __pdpu_bits;

typedef union {
	__pdpu_bits bits;
	__sfr_byte byte;
} __pdpu_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt1on : 1;
	unsigned char __pt1ck0 : 1;
	unsigned char __pt1ck1 : 1;
	unsigned char __pt1ck2 : 1;
	unsigned char __pt1pau : 1;
} __ptm1c0_bits;

typedef union {
	__ptm1c0_bits bits;
	__sfr_byte byte;
} __ptm1c0_type;

typedef struct {
	unsigned char __pt1cclr : 1;
	unsigned char __pt1capts : 1;
	unsigned char __pt1pol : 1;
	unsigned char __pt1oc : 1;
	unsigned char __pt1io0 : 1;
	unsigned char __pt1io1 : 1;
	unsigned char __pt1m0 : 1;
	unsigned char __pt1m1 : 1;
} __ptm1c1_bits;

typedef union {
	__ptm1c1_bits bits;
	__sfr_byte byte;
} __ptm1c1_type;

typedef struct {
	unsigned char : 3;
	unsigned char __pt2on : 1;
	unsigned char __pt2ck0 : 1;
	unsigned char __pt2ck1 : 1;
	unsigned char __pt2ck2 : 1;
	unsigned char __pt2pau : 1;
} __ptm2c0_bits;

typedef union {
	__ptm2c0_bits bits;
	__sfr_byte byte;
} __ptm2c0_type;

typedef struct {
	unsigned char __pt2cclr : 1;
	unsigned char __pt2capts : 1;
	unsigned char __pt2pol : 1;
	unsigned char __pt2oc : 1;
	unsigned char __pt2io0 : 1;
	unsigned char __pt2io1 : 1;
	unsigned char __pt2m0 : 1;
	unsigned char __pt2m1 : 1;
} __ptm2c1_bits;

typedef union {
	__ptm2c1_bits bits;
	__sfr_byte byte;
} __ptm2c1_type;

typedef struct {
	unsigned char __rd : 1;
	unsigned char __rden : 1;
	unsigned char __wr : 1;
	unsigned char __wren : 1;
	unsigned char : 4;
} __eec_bits;

typedef union {
	__eec_bits bits;
	__sfr_byte byte;
} __eec_type;

typedef struct {
	unsigned char __frd : 1;
	unsigned char __frden : 1;
	unsigned char __fwt : 1;
	unsigned char __fwpen : 1;
	unsigned char __fmod0 : 1;
	unsigned char __fmod1 : 1;
	unsigned char __fmod2 : 1;
	unsigned char __cfwen : 1;
} __fc0_bits;

typedef union {
	__fc0_bits bits;
	__sfr_byte byte;
} __fc0_type;

typedef struct {
	unsigned char __clwb : 1;
	unsigned char : 7;
} __fc2_bits;

typedef union {
	__fc2_bits bits;
	__sfr_byte byte;
} __fc2_type;

typedef struct {
	unsigned char __a0 : 1;
	unsigned char __a1 : 1;
	unsigned char __a2 : 1;
	unsigned char __a3 : 1;
	unsigned char __a4 : 1;
	unsigned char __a5 : 1;
	unsigned char __a6 : 1;
	unsigned char __a7 : 1;
} __farl_bits;

typedef union {
	__farl_bits bits;
	__sfr_byte byte;
} __farl_type;

typedef struct {
	unsigned char __a8 : 1;
	unsigned char __a9 : 1;
	unsigned char __a10 : 1;
	unsigned char __a11 : 1;
	unsigned char __a12 : 1;
	unsigned char : 3;
} __farh_bits;

typedef union {
	__farh_bits bits;
	__sfr_byte byte;
} __farh_type;

typedef struct {
	unsigned char __stckps : 1;
	unsigned char : 2;
	unsigned char __ptck2ps : 1;
	unsigned char : 2;
	unsigned char __ptp1ips : 1;
	unsigned char __ptp2ips : 1;
} __ifs0_bits;

typedef union {
	__ifs0_bits bits;
	__sfr_byte byte;
} __ifs0_type;

typedef struct {
	unsigned char __rxps0 : 1;
	unsigned char __rxps1 : 1;
	unsigned char : 2;
	unsigned char __sckaps : 1;
	unsigned char __sdiaps : 1;
	unsigned char __scsaps : 1;
	unsigned char : 1;
} __ifs1_bits;

typedef union {
	__ifs1_bits bits;
	__sfr_byte byte;
} __ifs1_type;

typedef struct {
	unsigned char __pas00 : 1;
	unsigned char __pas01 : 1;
	unsigned char __pas02 : 1;
	unsigned char __pas03 : 1;
	unsigned char __pas04 : 1;
	unsigned char __pas05 : 1;
	unsigned char __pas06 : 1;
	unsigned char __pas07 : 1;
} __pas0_bits;

typedef union {
	__pas0_bits bits;
	__sfr_byte byte;
} __pas0_type;

typedef struct {
	unsigned char __pas10 : 1;
	unsigned char __pas11 : 1;
	unsigned char __pas12 : 1;
	unsigned char __pas13 : 1;
	unsigned char __pas14 : 1;
	unsigned char __pas15 : 1;
	unsigned char __pas16 : 1;
	unsigned char __pas17 : 1;
} __pas1_bits;

typedef union {
	__pas1_bits bits;
	__sfr_byte byte;
} __pas1_type;

typedef struct {
	unsigned char __pbs00 : 1;
	unsigned char __pbs01 : 1;
	unsigned char __pbs02 : 1;
	unsigned char __pbs03 : 1;
	unsigned char __pbs04 : 1;
	unsigned char __pbs05 : 1;
	unsigned char __pbs06 : 1;
	unsigned char __pbs07 : 1;
} __pbs0_bits;

typedef union {
	__pbs0_bits bits;
	__sfr_byte byte;
} __pbs0_type;

typedef struct {
	unsigned char : 4;
	unsigned char __pds04 : 1;
	unsigned char __pds05 : 1;
	unsigned char __pds06 : 1;
	unsigned char __pds07 : 1;
} __pds0_bits;

typedef union {
	__pds0_bits bits;
	__sfr_byte byte;
} __pds0_type;

typedef struct {
	unsigned char __pcs00 : 1;
	unsigned char __pcs01 : 1;
	unsigned char : 2;
	unsigned char __pcs04 : 1;
	unsigned char __pcs05 : 1;
	unsigned char : 2;
} __pcs0_bits;

typedef union {
	__pcs0_bits bits;
	__sfr_byte byte;
} __pcs0_type;

typedef struct {
	unsigned char __pcs10 : 1;
	unsigned char __pcs11 : 1;
	unsigned char __pcs12 : 1;
	unsigned char __pcs13 : 1;
	unsigned char : 4;
} __pcs1_bits;

typedef union {
	__pcs1_bits bits;
	__sfr_byte byte;
} __pcs1_type;

typedef struct {
	unsigned char __sledc00 : 1;
	unsigned char __sledc01 : 1;
	unsigned char __sledc02 : 1;
	unsigned char __sledc03 : 1;
	unsigned char __sledc04 : 1;
	unsigned char __sledc05 : 1;
	unsigned char __sledc06 : 1;
	unsigned char __sledc07 : 1;
} __sledc0_bits;

typedef union {
	__sledc0_bits bits;
	__sfr_byte byte;
} __sledc0_type;

typedef struct {
	unsigned char __sledc10 : 1;
	unsigned char __sledc11 : 1;
	unsigned char __sledc12 : 1;
	unsigned char __sledc13 : 1;
	unsigned char __sledc14 : 1;
	unsigned char __sledc15 : 1;
	unsigned char : 2;
} __sledc1_bits;

typedef union {
	__sledc1_bits bits;
	__sfr_byte byte;
} __sledc1_type;


DEFINE_SFR(__sfr_byte, __mp0, 0x01);
DEFINE_SFR(__sfr_byte, __mp1l, 0x03);
DEFINE_SFR(__sfr_byte, __mp1h, 0x04);
DEFINE_SFR(__sfr_byte, __acc, 0x05);
DEFINE_SFR(__sfr_byte, __pcl, 0x06);
DEFINE_SFR(__sfr_byte, __tblp, 0x07);
DEFINE_SFR(__sfr_byte, __tblh, 0x08);
DEFINE_SFR(__sfr_byte, __tbhp, 0x09);
DEFINE_SFR(__status_type, __status, 0x0a);
DEFINE_SFR(__sfr_byte, __mp2l, 0x0d);
DEFINE_SFR(__sfr_byte, __mp2h, 0x0e);
DEFINE_SFR(__rstfc_type, __rstfc, 0x0f);
DEFINE_SFR(__scc_type, __scc, 0x10);
DEFINE_SFR(__hircc_type, __hircc, 0x11);
DEFINE_SFR(__hxtc_type, __hxtc, 0x12);
DEFINE_SFR(__lxtc_type, __lxtc, 0x13);
DEFINE_SFR(__pa_type, __pa, 0x14);
DEFINE_SFR(__pac_type, __pac, 0x15);
DEFINE_SFR(__papu_type, __papu, 0x16);
DEFINE_SFR(__pawu_type, __pawu, 0x17);
DEFINE_SFR(__rstc_type, __rstc, 0x18);
DEFINE_SFR(__lvrc_type, __lvrc, 0x19);
DEFINE_SFR(__lvdc_type, __lvdc, 0x1a);
DEFINE_SFR(__mfi0_type, __mfi0, 0x1b);
DEFINE_SFR(__mfi1_type, __mfi1, 0x1c);
DEFINE_SFR(__mfi2_type, __mfi2, 0x1d);
DEFINE_SFR(__wdtc_type, __wdtc, 0x1e);
DEFINE_SFR(__integ_type, __integ, 0x1f);
DEFINE_SFR(__intc0_type, __intc0, 0x20);
DEFINE_SFR(__intc1_type, __intc1, 0x21);
DEFINE_SFR(__intc2_type, __intc2, 0x22);
DEFINE_SFR(__intc3_type, __intc3, 0x23);
DEFINE_SFR(__pb_type, __pb, 0x24);
DEFINE_SFR(__pbc_type, __pbc, 0x25);
DEFINE_SFR(__pbpu_type, __pbpu, 0x26);
DEFINE_SFR(__pc_type, __pc, 0x27);
DEFINE_SFR(__pcc_type, __pcc, 0x28);
DEFINE_SFR(__pcpu_type, __pcpu, 0x29);
DEFINE_SFR(__pscr_type, __pscr, 0x2c);
DEFINE_SFR(__tb0c_type, __tb0c, 0x2d);
DEFINE_SFR(__tb1c_type, __tb1c, 0x2e);
DEFINE_SFR(__usr_type, __usr, 0x2f);
DEFINE_SFR(__ucr1_type, __ucr1, 0x30);
DEFINE_SFR(__ucr2_type, __ucr2, 0x31);
DEFINE_SFR(__sfr_byte, __txr_rxr, 0x32);
DEFINE_SFR(__sfr_byte, __brg, 0x33);
DEFINE_SFR(__simc0_type, __simc0, 0x34);
DEFINE_SFR(__simc1_type, __simc1, 0x35);
DEFINE_SFR(__sfr_byte, __simd, 0x36);
DEFINE_SFR(__sfr_byte, __sima, 0x37);
DEFINE_SFR(__simc2_type, __simc2, 0x37);
DEFINE_SFR(__simtoc_type, __simtoc, 0x38);
DEFINE_SFR(__spiac0_type, __spiac0, 0x3a);
DEFINE_SFR(__spiac1_type, __spiac1, 0x3b);
DEFINE_SFR(__sfr_byte, __spiad, 0x3c);
DEFINE_SFR(__eea_type, __eea, 0x41);
DEFINE_SFR(__eed_type, __eed, 0x42);
DEFINE_SFR(__stmc0_type, __stmc0, 0x49);
DEFINE_SFR(__stmc1_type, __stmc1, 0x4a);
DEFINE_SFR(__sfr_byte, __stmdl, 0x4b);
DEFINE_SFR(__sfr_byte, __stmdh, 0x4c);
DEFINE_SFR(__sfr_byte, __stmal, 0x4d);
DEFINE_SFR(__sfr_byte, __stmah, 0x4e);
DEFINE_SFR(__sfr_byte, __stmrp, 0x4f);
DEFINE_SFR(__ptm0c0_type, __ptm0c0, 0x50);
DEFINE_SFR(__ptm0c1_type, __ptm0c1, 0x51);
DEFINE_SFR(__sfr_byte, __ptm0dl, 0x52);
DEFINE_SFR(__sfr_byte, __ptm0dh, 0x53);
DEFINE_SFR(__sfr_byte, __ptm0al, 0x54);
DEFINE_SFR(__sfr_byte, __ptm0ah, 0x55);
DEFINE_SFR(__sfr_byte, __ptm0rpl, 0x56);
DEFINE_SFR(__sfr_byte, __ptm0rph, 0x57);
DEFINE_SFR(__sfr_byte, __mduwr0, 0x59);
DEFINE_SFR(__sfr_byte, __mduwr1, 0x5a);
DEFINE_SFR(__sfr_byte, __mduwr2, 0x5b);
DEFINE_SFR(__sfr_byte, __mduwr3, 0x5c);
DEFINE_SFR(__sfr_byte, __mduwr4, 0x5d);
DEFINE_SFR(__sfr_byte, __mduwr5, 0x5e);
DEFINE_SFR(__mduwctrl_type, __mduwctrl, 0x5f);
DEFINE_SFR(__adcs_type, __adcs, 0x65);
DEFINE_SFR(__adcr0_type, __adcr0, 0x66);
DEFINE_SFR(__adcr1_type, __adcr1, 0x67);
DEFINE_SFR(__pwrc_type, __pwrc, 0x68);
DEFINE_SFR(__pgac0_type, __pgac0, 0x69);
DEFINE_SFR(__pgac1_type, __pgac1, 0x6a);
DEFINE_SFR(__pgacs_type, __pgacs, 0x6b);
DEFINE_SFR(__sfr_byte, __adrl, 0x6c);
DEFINE_SFR(__sfr_byte, __adrm, 0x6d);
DEFINE_SFR(__sfr_byte, __adrh, 0x6e);
DEFINE_SFR(__sfr_byte, __dsdah, 0x70);
DEFINE_SFR(__sfr_byte, __dsdal, 0x71);
DEFINE_SFR(__dsdacc_type, __dsdacc, 0x72);
DEFINE_SFR(__sgc_type, __sgc, 0x73);
DEFINE_SFR(__sfr_byte, __sgn, 0x74);
DEFINE_SFR(__sfr_byte, __sgdnr, 0x75);
DEFINE_SFR(__opac_type, __opac, 0x76);
DEFINE_SFR(__swc0_type, __swc0, 0x77);
DEFINE_SFR(__swc1_type, __swc1, 0x78);
DEFINE_SFR(__swc2_type, __swc2, 0x79);
DEFINE_SFR(__sfr_byte, __daco, 0x7a);
DEFINE_SFR(__ftrc_type, __ftrc, 0x7b);
DEFINE_SFR(__pd_type, __pd, 0x7c);
DEFINE_SFR(__pdc_type, __pdc, 0x7d);
DEFINE_SFR(__pdpu_type, __pdpu, 0x7e);
DEFINE_SFR(__ptm1c0_type, __ptm1c0, 0x120);
DEFINE_SFR(__ptm1c1_type, __ptm1c1, 0x121);
DEFINE_SFR(__sfr_byte, __ptm1dl, 0x122);
DEFINE_SFR(__sfr_byte, __ptm1dh, 0x123);
DEFINE_SFR(__sfr_byte, __ptm1al, 0x124);
DEFINE_SFR(__sfr_byte, __ptm1ah, 0x125);
DEFINE_SFR(__sfr_byte, __ptm1rpl, 0x126);
DEFINE_SFR(__sfr_byte, __ptm1rph, 0x127);
DEFINE_SFR(__ptm2c0_type, __ptm2c0, 0x128);
DEFINE_SFR(__ptm2c1_type, __ptm2c1, 0x129);
DEFINE_SFR(__sfr_byte, __ptm2dl, 0x12a);
DEFINE_SFR(__sfr_byte, __ptm2dh, 0x12b);
DEFINE_SFR(__sfr_byte, __ptm2al, 0x12c);
DEFINE_SFR(__sfr_byte, __ptm2ah, 0x12d);
DEFINE_SFR(__sfr_byte, __ptm2rpl, 0x12e);
DEFINE_SFR(__sfr_byte, __ptm2rph, 0x12f);
DEFINE_SFR(__eec_type, __eec, 0x140);
DEFINE_SFR(__fc0_type, __fc0, 0x143);
DEFINE_SFR(__sfr_byte, __fc1, 0x144);
DEFINE_SFR(__fc2_type, __fc2, 0x145);
DEFINE_SFR(__farl_type, __farl, 0x146);
DEFINE_SFR(__farh_type, __farh, 0x147);
DEFINE_SFR(__sfr_byte, __fd0l, 0x148);
DEFINE_SFR(__sfr_byte, __fd0h, 0x149);
DEFINE_SFR(__sfr_byte, __fd1l, 0x14a);
DEFINE_SFR(__sfr_byte, __fd1h, 0x14b);
DEFINE_SFR(__sfr_byte, __fd2l, 0x14c);
DEFINE_SFR(__sfr_byte, __fd2h, 0x14d);
DEFINE_SFR(__sfr_byte, __fd3l, 0x14e);
DEFINE_SFR(__sfr_byte, __fd3h, 0x14f);
DEFINE_SFR(__ifs0_type, __ifs0, 0x150);
DEFINE_SFR(__ifs1_type, __ifs1, 0x151);
DEFINE_SFR(__pas0_type, __pas0, 0x153);
DEFINE_SFR(__pas1_type, __pas1, 0x154);
DEFINE_SFR(__pbs0_type, __pbs0, 0x155);
DEFINE_SFR(__pds0_type, __pds0, 0x156);
DEFINE_SFR(__pcs0_type, __pcs0, 0x157);
DEFINE_SFR(__pcs1_type, __pcs1, 0x158);
DEFINE_SFR(__sledc0_type, __sledc0, 0x159);
DEFINE_SFR(__sledc1_type, __sledc1, 0x15a);
DEFINE_SFR(__sfr_byte, __iar0, 0x00);
DEFINE_SFR(__sfr_byte, __iar1, 0x02);
DEFINE_SFR(__sfr_byte, __iar2, 0x0C);

#define _iar0     __iar0
#define _iar1     __iar1
#define _iar2     __iar2
#define _mp0      __mp0
#define _mp1l     __mp1l
#define _mp1h     __mp1h
#define _acc      __acc
#define _pcl      __pcl
#define _tblp     __tblp
#define _tblh     __tblh
#define _tbhp     __tbhp
#define _status   __status.byte
#define _mp2l     __mp2l
#define _mp2h     __mp2h
#define _rstfc    __rstfc.byte
#define _scc      __scc.byte
#define _hircc    __hircc.byte
#define _hxtc     __hxtc.byte
#define _lxtc     __lxtc.byte
#define _pa       __pa.byte
#define _pac      __pac.byte
#define _papu     __papu.byte
#define _pawu     __pawu.byte
#define _rstc     __rstc.byte
#define _lvrc     __lvrc.byte
#define _lvdc     __lvdc.byte
#define _mfi0     __mfi0.byte
#define _mfi1     __mfi1.byte
#define _mfi2     __mfi2.byte
#define _wdtc     __wdtc.byte
#define _integ    __integ.byte
#define _intc0    __intc0.byte
#define _intc1    __intc1.byte
#define _intc2    __intc2.byte
#define _intc3    __intc3.byte
#define _pb       __pb.byte
#define _pbc      __pbc.byte
#define _pbpu     __pbpu.byte
#define _pc       __pc.byte
#define _pcc      __pcc.byte
#define _pcpu     __pcpu.byte
#define _pscr     __pscr.byte
#define _tb0c     __tb0c.byte
#define _tb1c     __tb1c.byte
#define _usr      __usr.byte
#define _ucr1     __ucr1.byte
#define _ucr2     __ucr2.byte
#define _txr_rxr  __txr_rxr
#define _brg      __brg
#define _simc0    __simc0.byte
#define _simc1    __simc1.byte
#define _simd     __simd
#define _sima     __sima
#define _simc2    __simc2.byte
#define _simtoc   __simtoc.byte
#define _spiac0   __spiac0.byte
#define _spiac1   __spiac1.byte
#define _spiad    __spiad
#define _eea      __eea.byte
#define _eed      __eed.byte
#define _stmc0    __stmc0.byte
#define _stmc1    __stmc1.byte
#define _stmdl    __stmdl
#define _stmdh    __stmdh
#define _stmal    __stmal
#define _stmah    __stmah
#define _stmrp    __stmrp
#define _ptm0c0   __ptm0c0.byte
#define _ptm0c1   __ptm0c1.byte
#define _ptm0dl   __ptm0dl
#define _ptm0dh   __ptm0dh
#define _ptm0al   __ptm0al
#define _ptm0ah   __ptm0ah
#define _ptm0rpl  __ptm0rpl
#define _ptm0rph  __ptm0rph
#define _mduwr0   __mduwr0
#define _mduwr1   __mduwr1
#define _mduwr2   __mduwr2
#define _mduwr3   __mduwr3
#define _mduwr4   __mduwr4
#define _mduwr5   __mduwr5
#define _mduwctrl __mduwctrl.byte
#define _adcs     __adcs.byte
#define _adcr0    __adcr0.byte
#define _adcr1    __adcr1.byte
#define _pwrc     __pwrc.byte
#define _pgac0    __pgac0.byte
#define _pgac1    __pgac1.byte
#define _pgacs    __pgacs.byte
#define _adrl     __adrl
#define _adrm     __adrm
#define _adrh     __adrh
#define _dsdah    __dsdah
#define _dsdal    __dsdal
#define _dsdacc   __dsdacc.byte
#define _sgc      __sgc.byte
#define _sgn      __sgn
#define _sgdnr    __sgdnr
#define _opac     __opac.byte
#define _swc0     __swc0.byte
#define _swc1     __swc1.byte
#define _swc2     __swc2.byte
#define _daco     __daco
#define _ftrc     __ftrc.byte
#define _pd       __pd.byte
#define _pdc      __pdc.byte
#define _pdpu     __pdpu.byte
#define _ptm1c0   __ptm1c0.byte
#define _ptm1c1   __ptm1c1.byte
#define _ptm1dl   __ptm1dl
#define _ptm1dh   __ptm1dh
#define _ptm1al   __ptm1al
#define _ptm1ah   __ptm1ah
#define _ptm1rpl  __ptm1rpl
#define _ptm1rph  __ptm1rph
#define _ptm2c0   __ptm2c0.byte
#define _ptm2c1   __ptm2c1.byte
#define _ptm2dl   __ptm2dl
#define _ptm2dh   __ptm2dh
#define _ptm2al   __ptm2al
#define _ptm2ah   __ptm2ah
#define _ptm2rpl  __ptm2rpl
#define _ptm2rph  __ptm2rph
#define _eec      __eec.byte
#define _fc0      __fc0.byte
#define _fc1      __fc1
#define _fc2      __fc2.byte
#define _farl     __farl.byte
#define _farh     __farh.byte
#define _fd0l     __fd0l
#define _fd0h     __fd0h
#define _fd1l     __fd1l
#define _fd1h     __fd1h
#define _fd2l     __fd2l
#define _fd2h     __fd2h
#define _fd3l     __fd3l
#define _fd3h     __fd3h
#define _ifs0     __ifs0.byte
#define _ifs1     __ifs1.byte
#define _pas0     __pas0.byte
#define _pas1     __pas1.byte
#define _pbs0     __pbs0.byte
#define _pds0     __pds0.byte
#define _pcs0     __pcs0.byte
#define _pcs1     __pcs1.byte
#define _sledc0   __sledc0.byte
#define _sledc1   __sledc1.byte

#define _c        __status.bits.__c
#define _ac       __status.bits.__ac
#define _z        __status.bits.__z
#define _ov       __status.bits.__ov
#define _pdf      __status.bits.__pdf
#define _to       __status.bits.__to
#define _cz       __status.bits.__cz
#define _sc       __status.bits.__sc
#define _wrf      __rstfc.bits.__wrf
#define _lrf      __rstfc.bits.__lrf
#define _lvrf     __rstfc.bits.__lvrf
#define _rstf     __rstfc.bits.__rstf
#define _fsiden   __scc.bits.__fsiden
#define _fhiden   __scc.bits.__fhiden
#define _fss      __scc.bits.__fss
#define _fhs      __scc.bits.__fhs
#define _cks0     __scc.bits.__cks0
#define _cks1     __scc.bits.__cks1
#define _cks2     __scc.bits.__cks2
#define _hircen   __hircc.bits.__hircen
#define _hircf    __hircc.bits.__hircf
#define _hirc0    __hircc.bits.__hirc0
#define _hirc1    __hircc.bits.__hirc1
#define _hxten    __hxtc.bits.__hxten
#define _hxtf     __hxtc.bits.__hxtf
#define _hxtm     __hxtc.bits.__hxtm
#define _lxten    __lxtc.bits.__lxten
#define _lxtf     __lxtc.bits.__lxtf
#define _pa0      __pa.bits.__pa0
#define _pa1      __pa.bits.__pa1
#define _pa2      __pa.bits.__pa2
#define _pa3      __pa.bits.__pa3
#define _pa4      __pa.bits.__pa4
#define _pa5      __pa.bits.__pa5
#define _pa6      __pa.bits.__pa6
#define _pa7      __pa.bits.__pa7
#define _pac0     __pac.bits.__pac0
#define _pac1     __pac.bits.__pac1
#define _pac2     __pac.bits.__pac2
#define _pac3     __pac.bits.__pac3
#define _pac4     __pac.bits.__pac4
#define _pac5     __pac.bits.__pac5
#define _pac6     __pac.bits.__pac6
#define _pac7     __pac.bits.__pac7
#define _papu0    __papu.bits.__papu0
#define _papu1    __papu.bits.__papu1
#define _papu2    __papu.bits.__papu2
#define _papu3    __papu.bits.__papu3
#define _papu4    __papu.bits.__papu4
#define _papu5    __papu.bits.__papu5
#define _papu6    __papu.bits.__papu6
#define _papu7    __papu.bits.__papu7
#define _pawu0    __pawu.bits.__pawu0
#define _pawu1    __pawu.bits.__pawu1
#define _pawu2    __pawu.bits.__pawu2
#define _pawu3    __pawu.bits.__pawu3
#define _pawu4    __pawu.bits.__pawu4
#define _pawu5    __pawu.bits.__pawu5
#define _pawu6    __pawu.bits.__pawu6
#define _pawu7    __pawu.bits.__pawu7
#define _rstc0    __rstc.bits.__rstc0
#define _rstc1    __rstc.bits.__rstc1
#define _rstc2    __rstc.bits.__rstc2
#define _rstc3    __rstc.bits.__rstc3
#define _rstc4    __rstc.bits.__rstc4
#define _rstc5    __rstc.bits.__rstc5
#define _rstc6    __rstc.bits.__rstc6
#define _rstc7    __rstc.bits.__rstc7
#define _lvs0     __lvrc.bits.__lvs0
#define _lvs1     __lvrc.bits.__lvs1
#define _lvs2     __lvrc.bits.__lvs2
#define _lvs3     __lvrc.bits.__lvs3
#define _lvs4     __lvrc.bits.__lvs4
#define _lvs5     __lvrc.bits.__lvs5
#define _lvs6     __lvrc.bits.__lvs6
#define _lvs7     __lvrc.bits.__lvs7
#define _vlvd0    __lvdc.bits.__vlvd0
#define _vlvd1    __lvdc.bits.__vlvd1
#define _vlvd2    __lvdc.bits.__vlvd2
#define _vbgen    __lvdc.bits.__vbgen
#define _lvden    __lvdc.bits.__lvden
#define _lvdo     __lvdc.bits.__lvdo
#define _stmpe    __mfi0.bits.__stmpe
#define _stmae    __mfi0.bits.__stmae
#define _ptm0pe   __mfi0.bits.__ptm0pe
#define _ptm0ae   __mfi0.bits.__ptm0ae
#define _stmpf    __mfi0.bits.__stmpf
#define _stmaf    __mfi0.bits.__stmaf
#define _ptm0pf   __mfi0.bits.__ptm0pf
#define _ptm0af   __mfi0.bits.__ptm0af
#define _ptm1pe   __mfi1.bits.__ptm1pe
#define _ptm1ae   __mfi1.bits.__ptm1ae
#define _ptm2pe   __mfi1.bits.__ptm2pe
#define _ptm2ae   __mfi1.bits.__ptm2ae
#define _ptm1pf   __mfi1.bits.__ptm1pf
#define _ptm1af   __mfi1.bits.__ptm1af
#define _ptm2pf   __mfi1.bits.__ptm2pf
#define _ptm2af   __mfi1.bits.__ptm2af
#define _lve      __mfi2.bits.__lve
#define _dee      __mfi2.bits.__dee
#define _lvf      __mfi2.bits.__lvf
#define _def      __mfi2.bits.__def
#define _ws0      __wdtc.bits.__ws0
#define _ws1      __wdtc.bits.__ws1
#define _ws2      __wdtc.bits.__ws2
#define _we0      __wdtc.bits.__we0
#define _we1      __wdtc.bits.__we1
#define _we2      __wdtc.bits.__we2
#define _we3      __wdtc.bits.__we3
#define _we4      __wdtc.bits.__we4
#define _int0s0   __integ.bits.__int0s0
#define _int0s1   __integ.bits.__int0s1
#define _int1s0   __integ.bits.__int1s0
#define _int1s1   __integ.bits.__int1s1
#define _emi      __intc0.bits.__emi
#define _int0e    __intc0.bits.__int0e
#define _int1e    __intc0.bits.__int1e
#define _ade      __intc0.bits.__ade
#define _int0f    __intc0.bits.__int0f
#define _int1f    __intc0.bits.__int1f
#define _adf      __intc0.bits.__adf
#define _mf0e     __intc1.bits.__mf0e
#define _mf1e     __intc1.bits.__mf1e
#define _mf2e     __intc1.bits.__mf2e
#define _mf0f     __intc1.bits.__mf0f
#define _mf1f     __intc1.bits.__mf1f
#define _mf2f     __intc1.bits.__mf2f
#define _tb0e     __intc2.bits.__tb0e
#define _tb1e     __intc2.bits.__tb1e
#define _ure      __intc2.bits.__ure
#define _sime     __intc2.bits.__sime
#define _tb0f     __intc2.bits.__tb0f
#define _tb1f     __intc2.bits.__tb1f
#define _urf      __intc2.bits.__urf
#define _simf     __intc2.bits.__simf
#define _spiae    __intc3.bits.__spiae
#define _spiaf    __intc3.bits.__spiaf
#define _pb0      __pb.bits.__pb0
#define _pb1      __pb.bits.__pb1
#define _pb2      __pb.bits.__pb2
#define _pb3      __pb.bits.__pb3
#define _pb4      __pb.bits.__pb4
#define _pb5      __pb.bits.__pb5
#define _pb6      __pb.bits.__pb6
#define _pb7      __pb.bits.__pb7
#define _pbc0     __pbc.bits.__pbc0
#define _pbc1     __pbc.bits.__pbc1
#define _pbc2     __pbc.bits.__pbc2
#define _pbc3     __pbc.bits.__pbc3
#define _pbc4     __pbc.bits.__pbc4
#define _pbc5     __pbc.bits.__pbc5
#define _pbc6     __pbc.bits.__pbc6
#define _pbc7     __pbc.bits.__pbc7
#define _pbpu0    __pbpu.bits.__pbpu0
#define _pbpu1    __pbpu.bits.__pbpu1
#define _pbpu2    __pbpu.bits.__pbpu2
#define _pbpu3    __pbpu.bits.__pbpu3
#define _pbpu4    __pbpu.bits.__pbpu4
#define _pbpu5    __pbpu.bits.__pbpu5
#define _pbpu6    __pbpu.bits.__pbpu6
#define _pbpu7    __pbpu.bits.__pbpu7
#define _pc0      __pc.bits.__pc0
#define _pc1      __pc.bits.__pc1
#define _pc2      __pc.bits.__pc2
#define _pc3      __pc.bits.__pc3
#define _pc4      __pc.bits.__pc4
#define _pc5      __pc.bits.__pc5
#define _pc6      __pc.bits.__pc6
#define _pc7      __pc.bits.__pc7
#define _pcc0     __pcc.bits.__pcc0
#define _pcc1     __pcc.bits.__pcc1
#define _pcc2     __pcc.bits.__pcc2
#define _pcc3     __pcc.bits.__pcc3
#define _pcc4     __pcc.bits.__pcc4
#define _pcc5     __pcc.bits.__pcc5
#define _pcc6     __pcc.bits.__pcc6
#define _pcc7     __pcc.bits.__pcc7
#define _pcpu0    __pcpu.bits.__pcpu0
#define _pcpu1    __pcpu.bits.__pcpu1
#define _pcpu2    __pcpu.bits.__pcpu2
#define _pcpu3    __pcpu.bits.__pcpu3
#define _pcpu4    __pcpu.bits.__pcpu4
#define _pcpu5    __pcpu.bits.__pcpu5
#define _pcpu6    __pcpu.bits.__pcpu6
#define _pcpu7    __pcpu.bits.__pcpu7
#define _clksel0  __pscr.bits.__clksel0
#define _clksel1  __pscr.bits.__clksel1
#define _tb00     __tb0c.bits.__tb00
#define _tb01     __tb0c.bits.__tb01
#define _tb02     __tb0c.bits.__tb02
#define _tb0on    __tb0c.bits.__tb0on
#define _tb10     __tb1c.bits.__tb10
#define _tb11     __tb1c.bits.__tb11
#define _tb12     __tb1c.bits.__tb12
#define _tb1on    __tb1c.bits.__tb1on
#define _txif     __usr.bits.__txif
#define _tidle    __usr.bits.__tidle
#define _rxif     __usr.bits.__rxif
#define _ridle    __usr.bits.__ridle
#define _oerr     __usr.bits.__oerr
#define _ferr     __usr.bits.__ferr
#define _nf       __usr.bits.__nf
#define _perr     __usr.bits.__perr
#define _tx8      __ucr1.bits.__tx8
#define _rx8      __ucr1.bits.__rx8
#define _txbrk    __ucr1.bits.__txbrk
#define _stops    __ucr1.bits.__stops
#define _prt      __ucr1.bits.__prt
#define _pren     __ucr1.bits.__pren
#define _bno      __ucr1.bits.__bno
#define _uarten   __ucr1.bits.__uarten
#define _teie     __ucr2.bits.__teie
#define _tiie     __ucr2.bits.__tiie
#define _rie      __ucr2.bits.__rie
#define _wake     __ucr2.bits.__wake
#define _adden    __ucr2.bits.__adden
#define _brgh     __ucr2.bits.__brgh
#define _rxen     __ucr2.bits.__rxen
#define _txen     __ucr2.bits.__txen
#define _simicf   __simc0.bits.__simicf
#define _simen    __simc0.bits.__simen
#define _simdeb0  __simc0.bits.__simdeb0
#define _simdeb1  __simc0.bits.__simdeb1
#define _sim0     __simc0.bits.__sim0
#define _sim1     __simc0.bits.__sim1
#define _sim2     __simc0.bits.__sim2
#define _rxak     __simc1.bits.__rxak
#define _iamwu    __simc1.bits.__iamwu
#define _srw      __simc1.bits.__srw
#define _txak     __simc1.bits.__txak
#define _htx      __simc1.bits.__htx
#define _hbb      __simc1.bits.__hbb
#define _haas     __simc1.bits.__haas
#define _hcf      __simc1.bits.__hcf
#define _trf      __simc2.bits.__trf
#define _wcol     __simc2.bits.__wcol
#define _csen     __simc2.bits.__csen
#define _mls      __simc2.bits.__mls
#define _ckeg     __simc2.bits.__ckeg
#define _ckpolb   __simc2.bits.__ckpolb
#define _simtos0  __simtoc.bits.__simtos0
#define _simtos1  __simtoc.bits.__simtos1
#define _simtos2  __simtoc.bits.__simtos2
#define _simtos3  __simtoc.bits.__simtos3
#define _simtos4  __simtoc.bits.__simtos4
#define _simtos5  __simtoc.bits.__simtos5
#define _simtof   __simtoc.bits.__simtof
#define _simtoen  __simtoc.bits.__simtoen
#define _spiaicf  __spiac0.bits.__spiaicf
#define _spiaen   __spiac0.bits.__spiaen
#define _saspi0   __spiac0.bits.__saspi0
#define _saspi1   __spiac0.bits.__saspi1
#define _saspi2   __spiac0.bits.__saspi2
#define _satrf    __spiac1.bits.__satrf
#define _sawcol   __spiac1.bits.__sawcol
#define _sacsen   __spiac1.bits.__sacsen
#define _samls    __spiac1.bits.__samls
#define _sackeg   __spiac1.bits.__sackeg
#define _sackpolb __spiac1.bits.__sackpolb
#define _eea0     __eea.bits.__eea0
#define _eea1     __eea.bits.__eea1
#define _eea2     __eea.bits.__eea2
#define _eea3     __eea.bits.__eea3
#define _eea4     __eea.bits.__eea4
#define _eea5     __eea.bits.__eea5
#define _eed0     __eed.bits.__eed0
#define _eed1     __eed.bits.__eed1
#define _eed2     __eed.bits.__eed2
#define _eed3     __eed.bits.__eed3
#define _eed4     __eed.bits.__eed4
#define _eed5     __eed.bits.__eed5
#define _eed6     __eed.bits.__eed6
#define _eed7     __eed.bits.__eed7
#define _ston     __stmc0.bits.__ston
#define _stck0    __stmc0.bits.__stck0
#define _stck1    __stmc0.bits.__stck1
#define _stck2    __stmc0.bits.__stck2
#define _stpau    __stmc0.bits.__stpau
#define _stcclr   __stmc1.bits.__stcclr
#define _stdpx    __stmc1.bits.__stdpx
#define _stpol    __stmc1.bits.__stpol
#define _stoc     __stmc1.bits.__stoc
#define _stio0    __stmc1.bits.__stio0
#define _stio1    __stmc1.bits.__stio1
#define _stm0     __stmc1.bits.__stm0
#define _stm1     __stmc1.bits.__stm1
#define _pt0on    __ptm0c0.bits.__pt0on
#define _pt0ck0   __ptm0c0.bits.__pt0ck0
#define _pt0ck1   __ptm0c0.bits.__pt0ck1
#define _pt0ck2   __ptm0c0.bits.__pt0ck2
#define _pt0pau   __ptm0c0.bits.__pt0pau
#define _pt0cclr  __ptm0c1.bits.__pt0cclr
#define _pt0capts __ptm0c1.bits.__pt0capts
#define _pt0pol   __ptm0c1.bits.__pt0pol
#define _pt0oc    __ptm0c1.bits.__pt0oc
#define _pt0io0   __ptm0c1.bits.__pt0io0
#define _pt0io1   __ptm0c1.bits.__pt0io1
#define _pt0m0    __ptm0c1.bits.__pt0m0
#define _pt0m1    __ptm0c1.bits.__pt0m1
#define _mdwov    __mduwctrl.bits.__mdwov
#define _mdwef    __mduwctrl.bits.__mdwef
#define _adck0    __adcs.bits.__adck0
#define _adck1    __adcs.bits.__adck1
#define _adck2    __adcs.bits.__adck2
#define _adck3    __adcs.bits.__adck3
#define _adck4    __adcs.bits.__adck4
#define _vrefs    __adcr0.bits.__vrefs
#define _ador0    __adcr0.bits.__ador0
#define _ador1    __adcr0.bits.__ador1
#define _ador2    __adcr0.bits.__ador2
#define _adoff    __adcr0.bits.__adoff
#define _adslp    __adcr0.bits.__adslp
#define _adrst    __adcr0.bits.__adrst
#define _eoc      __adcr1.bits.__eoc
#define _adcdl    __adcr1.bits.__adcdl
#define _vrbufp   __adcr1.bits.__vrbufp
#define _vrbufn   __adcr1.bits.__vrbufn
#define _flms0    __adcr1.bits.__flms0
#define _flms1    __adcr1.bits.__flms1
#define _flms2    __adcr1.bits.__flms2
#define _ldovs0   __pwrc.bits.__ldovs0
#define _ldovs1   __pwrc.bits.__ldovs1
#define _ldobps   __pwrc.bits.__ldobps
#define _ldoen    __pwrc.bits.__ldoen
#define _pgs0     __pgac0.bits.__pgs0
#define _pgs1     __pgac0.bits.__pgs1
#define _pgs2     __pgac0.bits.__pgs2
#define _ags0     __pgac0.bits.__ags0
#define _ags1     __pgac0.bits.__ags1
#define _vgs0     __pgac0.bits.__vgs0
#define _vgs1     __pgac0.bits.__vgs1
#define _dcset0   __pgac1.bits.__dcset0
#define _dcset1   __pgac1.bits.__dcset1
#define _dcset2   __pgac1.bits.__dcset2
#define _inx0     __pgac1.bits.__inx0
#define _inx1     __pgac1.bits.__inx1
#define _inis     __pgac1.bits.__inis
#define _chsp0    __pgacs.bits.__chsp0
#define _chsp1    __pgacs.bits.__chsp1
#define _chsp2    __pgacs.bits.__chsp2
#define _chsp3    __pgacs.bits.__chsp3
#define _chsn0    __pgacs.bits.__chsn0
#define _chsn1    __pgacs.bits.__chsn1
#define _chsn2    __pgacs.bits.__chsn2
#define _chsn3    __pgacs.bits.__chsn3
#define _dsdacvrs0 __dsdacc.bits.__dsdacvrs0
#define _dsdacvrs1 __dsdacc.bits.__dsdacvrs1
#define _dsdacen  __dsdacc.bits.__dsdacen
#define _bren     __sgc.bits.__bren
#define _d0       __sgc.bits.__d0
#define _d1       __sgc.bits.__d1
#define _sgen     __sgc.bits.__sgen
#define _op2g0    __opac.bits.__op2g0
#define _op2g1    __opac.bits.__op2g1
#define _op2g2    __opac.bits.__op2g2
#define _op2g3    __opac.bits.__op2g3
#define _opaen    __opac.bits.__opaen
#define _vfl2     __swc0.bits.__vfl2
#define _ifl1     __swc0.bits.__ifl1
#define _vfr1     __swc0.bits.__vfr1
#define _ifr2     __swc0.bits.__ifr2
#define _vhl2     __swc0.bits.__vhl2
#define _ihl1     __swc0.bits.__ihl1
#define _vhr1     __swc0.bits.__vhr1
#define _ihr2     __swc0.bits.__ihr2
#define _irf2     __swc1.bits.__irf2
#define _vrfp2    __swc1.bits.__vrfp2
#define _irf1     __swc1.bits.__irf1
#define _vrfp1    __swc1.bits.__vrfp1
#define _vrfn     __swc1.bits.__vrfn
#define _ihl2     __swc1.bits.__ihl2
#define _vhl1     __swc1.bits.__vhl1
#define _ifr1     __swc2.bits.__ifr1
#define _ifl2     __swc2.bits.__ifl2
#define _vfr2     __swc2.bits.__vfr2
#define _vfl1     __swc2.bits.__vfl1
#define _ihr1     __swc2.bits.__ihr1
#define _vhr2     __swc2.bits.__vhr2
#define _sw18     __ftrc.bits.__sw18
#define _sw19     __ftrc.bits.__sw19
#define _hysen    __ftrc.bits.__hysen
#define _ftren    __ftrc.bits.__ftren
#define _pd0      __pd.bits.__pd0
#define _pd1      __pd.bits.__pd1
#define _pd2      __pd.bits.__pd2
#define _pd3      __pd.bits.__pd3
#define _pdc0     __pdc.bits.__pdc0
#define _pdc1     __pdc.bits.__pdc1
#define _pdc2     __pdc.bits.__pdc2
#define _pdc3     __pdc.bits.__pdc3
#define _pdpu0    __pdpu.bits.__pdpu0
#define _pdpu1    __pdpu.bits.__pdpu1
#define _pdpu2    __pdpu.bits.__pdpu2
#define _pdpu3    __pdpu.bits.__pdpu3
#define _pt1on    __ptm1c0.bits.__pt1on
#define _pt1ck0   __ptm1c0.bits.__pt1ck0
#define _pt1ck1   __ptm1c0.bits.__pt1ck1
#define _pt1ck2   __ptm1c0.bits.__pt1ck2
#define _pt1pau   __ptm1c0.bits.__pt1pau
#define _pt1cclr  __ptm1c1.bits.__pt1cclr
#define _pt1capts __ptm1c1.bits.__pt1capts
#define _pt1pol   __ptm1c1.bits.__pt1pol
#define _pt1oc    __ptm1c1.bits.__pt1oc
#define _pt1io0   __ptm1c1.bits.__pt1io0
#define _pt1io1   __ptm1c1.bits.__pt1io1
#define _pt1m0    __ptm1c1.bits.__pt1m0
#define _pt1m1    __ptm1c1.bits.__pt1m1
#define _pt2on    __ptm2c0.bits.__pt2on
#define _pt2ck0   __ptm2c0.bits.__pt2ck0
#define _pt2ck1   __ptm2c0.bits.__pt2ck1
#define _pt2ck2   __ptm2c0.bits.__pt2ck2
#define _pt2pau   __ptm2c0.bits.__pt2pau
#define _pt2cclr  __ptm2c1.bits.__pt2cclr
#define _pt2capts __ptm2c1.bits.__pt2capts
#define _pt2pol   __ptm2c1.bits.__pt2pol
#define _pt2oc    __ptm2c1.bits.__pt2oc
#define _pt2io0   __ptm2c1.bits.__pt2io0
#define _pt2io1   __ptm2c1.bits.__pt2io1
#define _pt2m0    __ptm2c1.bits.__pt2m0
#define _pt2m1    __ptm2c1.bits.__pt2m1
#define _rd       __eec.bits.__rd
#define _rden     __eec.bits.__rden
#define _wr       __eec.bits.__wr
#define _wren     __eec.bits.__wren
#define _frd      __fc0.bits.__frd
#define _frden    __fc0.bits.__frden
#define _fwt      __fc0.bits.__fwt
#define _fwpen    __fc0.bits.__fwpen
#define _fmod0    __fc0.bits.__fmod0
#define _fmod1    __fc0.bits.__fmod1
#define _fmod2    __fc0.bits.__fmod2
#define _cfwen    __fc0.bits.__cfwen
#define _clwb     __fc2.bits.__clwb
#define _a0       __farl.bits.__a0
#define _a1       __farl.bits.__a1
#define _a2       __farl.bits.__a2
#define _a3       __farl.bits.__a3
#define _a4       __farl.bits.__a4
#define _a5       __farl.bits.__a5
#define _a6       __farl.bits.__a6
#define _a7       __farl.bits.__a7
#define _a8       __farh.bits.__a8
#define _a9       __farh.bits.__a9
#define _a10      __farh.bits.__a10
#define _a11      __farh.bits.__a11
#define _a12      __farh.bits.__a12
#define _stckps   __ifs0.bits.__stckps
#define _ptck2ps  __ifs0.bits.__ptck2ps
#define _ptp1ips  __ifs0.bits.__ptp1ips
#define _ptp2ips  __ifs0.bits.__ptp2ips
#define _rxps0    __ifs1.bits.__rxps0
#define _rxps1    __ifs1.bits.__rxps1
#define _sckaps   __ifs1.bits.__sckaps
#define _sdiaps   __ifs1.bits.__sdiaps
#define _scsaps   __ifs1.bits.__scsaps
#define _pas00    __pas0.bits.__pas00
#define _pas01    __pas0.bits.__pas01
#define _pas02    __pas0.bits.__pas02
#define _pas03    __pas0.bits.__pas03
#define _pas04    __pas0.bits.__pas04
#define _pas05    __pas0.bits.__pas05
#define _pas06    __pas0.bits.__pas06
#define _pas07    __pas0.bits.__pas07
#define _pas10    __pas1.bits.__pas10
#define _pas11    __pas1.bits.__pas11
#define _pas12    __pas1.bits.__pas12
#define _pas13    __pas1.bits.__pas13
#define _pas14    __pas1.bits.__pas14
#define _pas15    __pas1.bits.__pas15
#define _pas16    __pas1.bits.__pas16
#define _pas17    __pas1.bits.__pas17
#define _pbs00    __pbs0.bits.__pbs00
#define _pbs01    __pbs0.bits.__pbs01
#define _pbs02    __pbs0.bits.__pbs02
#define _pbs03    __pbs0.bits.__pbs03
#define _pbs04    __pbs0.bits.__pbs04
#define _pbs05    __pbs0.bits.__pbs05
#define _pbs06    __pbs0.bits.__pbs06
#define _pbs07    __pbs0.bits.__pbs07
#define _pds04    __pds0.bits.__pds04
#define _pds05    __pds0.bits.__pds05
#define _pds06    __pds0.bits.__pds06
#define _pds07    __pds0.bits.__pds07
#define _pcs00    __pcs0.bits.__pcs00
#define _pcs01    __pcs0.bits.__pcs01
#define _pcs04    __pcs0.bits.__pcs04
#define _pcs05    __pcs0.bits.__pcs05
#define _pcs10    __pcs1.bits.__pcs10
#define _pcs11    __pcs1.bits.__pcs11
#define _pcs12    __pcs1.bits.__pcs12
#define _pcs13    __pcs1.bits.__pcs13
#define _sledc00  __sledc0.bits.__sledc00
#define _sledc01  __sledc0.bits.__sledc01
#define _sledc02  __sledc0.bits.__sledc02
#define _sledc03  __sledc0.bits.__sledc03
#define _sledc04  __sledc0.bits.__sledc04
#define _sledc05  __sledc0.bits.__sledc05
#define _sledc06  __sledc0.bits.__sledc06
#define _sledc07  __sledc0.bits.__sledc07
#define _sledc10  __sledc1.bits.__sledc10
#define _sledc11  __sledc1.bits.__sledc11
#define _sledc12  __sledc1.bits.__sledc12
#define _sledc13  __sledc1.bits.__sledc13
#define _sledc14  __sledc1.bits.__sledc14
#define _sledc15  __sledc1.bits.__sledc15

#define ___mkstr(x)                #x
#define __EEPROM_DATA(a, b, c, d, e, f, g, h) \
                         asm("eeprom_data .section 'eeprom'"); \
                         asm("db\t" ___mkstr(a));        \
                         asm("db\t" ___mkstr(b));        \
                         asm("db\t" ___mkstr(c));        \
                         asm("db\t" ___mkstr(d));        \
                         asm("db\t" ___mkstr(e));        \
                         asm("db\t" ___mkstr(f));        \
                         asm("db\t" ___mkstr(g));        \
                         asm("db\t" ___mkstr(h));        

#endif // _BH66F2650_H_
